env:
  browser: true
  es6: true
  jasmine: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: script
rules:
  indent:
    - 2
    - tab
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
